# CHANGE THIS TO YOUR OWN DATASET
TTS_dataset: "danyw24/colombian-natural-speech-0.2-Llama3.2-7k"

model_name: "danyw24/argos-3b-0.1-es"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 6000
learning_rate: 3.0e-5

# Naming and paths
save_folder: "checkpoints"
project_name: "tuning-orpheus"
run_name: "Argos-8k-128-loRA"